baseURL = "https://yalinliu.org/"
languageCode = "zh-cn"
defaultContentLanguage = "cn"
defaultContentLanguageInSubdir = false
title = "Yalin"
theme = "hugo-ht"
enableRobotsTXT = true
enableGitInfo = true
footnotereturnlinkcontents = "↩"


[module.hugoVersion]
  min = "0.147.9"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = false
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[imaging]
  quality = 80

[params]
  MathJaxCDN = "https://cdn.jsdelivr.net/npm"
  MathJaxVersion = "4"
  favicon = "https://assets.yalinliu.org/icon.jpg"
  GithubRepo = "https://github.com/Wertherliu/mysite"
  blogDirName = "posts"
  logo = { url = "https://assets.yalinliu.org/logo.jpg",  alt = "Yalin's Website" }


[languages]

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "Yalin Liu | 刘亚林"
    contentDir = "content/en"

    [languages.en.params]
      description = "Personal website of Yalin"
      licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    
    [languages.en.taxonomies]
      tag = "tags"
      category = "categories"

    [languages.en.permalinks]
      posts = ":year/:month/:day/:slug/"

    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1

    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 3

    [[languages.en.menu.main]]
      name = "Article"
      url = "/article/"
      weight = 4

    [[languages.en.menu.main]]
      name = "Tutorial"
      url = "/study/"
      weight = 5

  [languages.cn]
    languageName = "中文"
    languageCode = "zh-cn"
    weight = 2
    title = "刘亚林 | Yalin Liu"
    contentDir = "content/cn"

    [languages.cn.params]
      description = "刘亚林的个人网站"
      licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans"

    [languages.cn.taxonomies]
      tag = "tags"
      category = "categories"

    [languages.cn.permalinks]
      posts = ":year/:month/:day/:slug/"

    [[languages.cn.menu.main]]
      name = "首页"
      url = "/"
      weight = 1

    [[languages.cn.menu.main]]
      name = "关于"
      url = "/about/"
      weight = 2

    [[languages.cn.menu.main]]
      name = "博客"
      url = "/posts/"
      weight = 3
    
    [[languages.cn.menu.main]]
      name = "文章"
      url = "/article/"
      weight = 4

    [[languages.cn.menu.main]]
      name = "学习"
      url = "/study/"
      weight = 5



    
